development:
  access_key_id: 0XVAQR64TGCGWZ4W37R2
  secret_access_key: 2mkUk7BxE4fVu7J4zCmVGnhIL3kXQGn8GaEpl5QR
  bucket_name: fogboundpictures
  
test:
  access_key_id: 0XVAQR64TGCGWZ4W37R2
  secret_access_key: 2mkUk7BxE4fVu7J4zCmVGnhIL3kXQGn8GaEpl5QR
  bucket_name: fogboundpictures

production:
  access_key_id: 0XVAQR64TGCGWZ4W37R2
  secret_access_key: 2mkUk7BxE4fVu7J4zCmVGnhIL3kXQGn8GaEpl5QR
  bucket_name: fogboundpictures
